### ISSUE TITLE
Testing probando

### ISSUE THREAD

**Issue by delcabo** [caom92/Espresso#166]
Probando Nuevo metodo de solicitud

Antes recuerdo que podia mover los ITEMS de lugar...

Hoy no me deja hacerlos en las bitacoras...
![image](https://cloud.githubusercontent.com/assets/28766240/26178086/60acd8e4-3b11-11e7-847a-a916c9587e38.png)

saludos

**Comment by caom92** [comment]
@VMiracle corrigió el error, esa parte del código al parecer estaba comentada. Arreglamos otros errores que encontramos mientras buscábamos la causa de este error y todos los cambios los subimos al servidor, por lo que ya debería de poder reordenarse los objetos de esa bitácora
