### ISSUE TITLE
Preo Op no quiere abrir pantalla completa

### ISSUE THREAD

**Issue by delcabo** [caom92/Espresso#168]
Hola buendia

No quiso abrir la pantalla complete para camptura de preop en general todas las zonas
![image](https://cloud.githubusercontent.com/assets/28766240/26207299/fb9f127e-3b9b-11e7-9a72-a49873b45298.png)

saludos # #

**Comment by delcabo** [comment]
Y en todos las bitacoras lo mismo ... solo habre el encabezado...

saludos

**Comment by caom92** [comment]
A mi si me abre, intente borrar el cache de su computadora y dígame si eso solucionó el problema o no

![screenshot_2017-05-18_13-27-48](https://cloud.githubusercontent.com/assets/9997614/26222161/d0954f76-3bcd-11e7-8d1f-0ca1ac1ae24e.png)

**Comment by delcabo** [comment]
gracias Carlos, ya le hice asi como me dijiste y me funciono
ahora envio nota a los demas para que lo hagan!!!
