### ISSUE TITLE
pone 0 cuando quieres dar de alta 1 ITEM nuevo pero solo a WILMA raro!!

### ISSUE THREAD

**Issue by delcabo** [caom92/Espresso#169]
Buen dia, no he podido terminar la bitacora de pest control de BCN, curioso el dato pone 0 en # de item cuando le doy agregar... 

![image](https://cloud.githubusercontent.com/assets/28766240/26208413/dd993c5c-3b9e-11e7-8026-e453b20786d9.png)

saludos

**Comment by delcabo** [comment]
mismo detalle en dar de alta proveedores
![image](https://cloud.githubusercontent.com/assets/28766240/26212919/0f9339c6-3bac-11e7-967c-ed904f7363ba.png)

**Comment by caom92** [comment]
De nuevo, yo si pude agregar si problemas. Revise borrando el caché de su navegador y vuelva a intentar. 

![screenshot_2017-05-18_13-34-36](https://cloud.githubusercontent.com/assets/9997614/26222438/ccde05de-3bce-11e7-99a2-66d340705729.png)
![screenshot_2017-05-18_13-30-38](https://cloud.githubusercontent.com/assets/9997614/26222437/ccdcb2a6-3bce-11e7-85eb-22435e6e47e4.png)
