### ISSUE TITLE
Desplegar mensajes descriptivos en todos los toasts del sistema

### ISSUE THREAD

**Issue by caom92** [caom92/Espresso#171]
En todos los formularios del sistema, cada vez que ocurre un error de validación de entrada de usuario o un error en la comunicación con el servidor, se debe desplegar un toast con un mensaje de texto apropiado y que describa claramente cual fue el problema. Actualmente muchos de estos toasts son ambiguos y confunden más al usuario que ayudarlo a entender qué salió mal.

**Comment by VMiracle** [comment]
Idealmente se deben de crear mensajes de error específicos para cada campo, pero en lo que estos se vayan añadiendo se deben de dejar los mensajes genéricos
