### ISSUE TITLE
ATP 

### ISSUE THREAD

**Issue by delcabo** [caom92/Espresso#183]
Hola chicos, revisando el ATP, no me deja dar de alta areas y items (igualito a la forma de Preops) pero sin usar lo de preops (es totalmente independiente)
![image](https://cloud.githubusercontent.com/assets/28766240/26225297/535b0128-3bdb-11e7-8444-48c133c56687.png)

**Comment by caom92** [comment]
Esto es parte de los cambios considerados en #178
