### ISSUE TITLE
Finish Product Check

### ISSUE THREAD

**Issue by delcabo** [caom92/Espresso#184]
Equipo no comprendo porque en este modulo tengo que dar de alta items... ??

si es una table espeficia donde usaria los datos de proveedor, codigo  y clients  bla bla bla..

saludos

**Comment by caom92** [comment]
No entiendo su pregunta Julio. ¿Porqué dice que debe dar de alta ítems?

**Comment by delcabo** [comment]
lo que pasa es que a este bitacora, no sigue las misas area o items qu Preoperativos
se usan area o items aleatorios dia con dia!
tal vez ya tienes pensado, que este campo de LOCATION sea abierto...
??  y cada quien le ponga los datos... tal vez unos 6-10 espacios... abierto por dia... 

![image](https://cloud.githubusercontent.com/assets/28766240/26258633/5d436e6a-3c7a-11e7-95a9-c5d5534c370b.png)

**Comment by caom92** [comment]
Se confundió de bitacora Julio, este thread es exclusivamente para Finished Product, para hablar de ATP tiene que visitar #183 (el cual por cierto, usted cerró, no sé porque). Usted dice que debe dar de alta ítems en esta bitacora. Su pregunta me confunde porque para esta bitacora no hay inventario, por lo que no hay forma de agregar ítems. Las únicas tablas auxiliares que esta bitacora utiliza son las de clientes, proveedores y productos, los cuales deben ser capturados por el Administrador. Los campos de Batch, y origin son abiertos, pero los campos de proveedores, producto y cliente son listas de selección cuyas opciones deben ser dadas de alta por el administrador.

**Comment by delcabo** [comment]
jjijiji sorry...

aa la cerre porque esta la #170 Abierta dije, pues cualquier cosa ahi pongo....  tambien es cierto ya lo tienes previsto esto de no items...   

llisto con la finish product check.. GRACIAS!!

**Comment by delcabo** [comment]
Bueno me falta com dar de altas AREAS
![image](https://cloud.githubusercontent.com/assets/28766240/26260424/01fd0aea-3c82-11e7-9ccc-1eab5f282edc.png)

**Comment by caom92** [comment]
si de hecho ya lo reporté en #189 , @VMiracle  lo arreglará en cuanto termine de trabajar en la bitacora de Unusual Occurrence
