### ISSUE TITLE
Pest Control

### ISSUE THREAD

**Issue by delcabo** [caom92/Espresso#188]
Acbao de dar de alta a 2 (Esteban y FranciscoH) usuarios para pest control BCN y no quiere abrir la pagina de captura... al momento de click self Inspection button, me dio 3 veces "Some Error" pero continuaba...

![image](https://cloud.githubusercontent.com/assets/28766240/26259047/1730562a-3c7c-11e7-8c01-dde8b5359b89.png)

**Comment by caom92** [comment]
Este es un error en el servidor.

**Comment by caom92** [comment]
También es duplicado de #186

**Comment by caom92** [comment]
Ya quedó corregido
