### ISSUE TITLE
como Director no salen datos

### ISSUE THREAD

**Issue by delcabo** [caom92/Espresso#190]
Buen dia, revisando como usuario director no se ven los registros... :(

de ninguna bitacora!!

![image](https://cloud.githubusercontent.com/assets/28766240/26315523/46571a64-3ec6-11e7-8574-0597f53a8509.png)

**Comment by caom92** [comment]
Parece que ya está funcionando

![screenshot_2017-05-22_11-33-35](https://cloud.githubusercontent.com/assets/9997614/26323137/8cefd92c-3ee2-11e7-81a9-42ca2318e748.png)
