### ISSUE TITLE
En la pantalla de reporte, se pide un servicio fuera de lugar

### ISSUE THREAD

**Issue by caom92** [caom92/Espresso#191]
Como usuario director, en la pantalla de desplegar reporte, justo después de seleccionar una bitacora, se ejecuta el servicio list-privileges-gmp-packing-preop, sin importar la bitacora elegida. Naturalmente, como este servicio no puede ser ejecutado por el director, el servicio truena y dispara un toast en la pantalla.

**Comment by VMiracle** [comment]
Ya subí un fix con una verificación que debería evitar que el director solicite este servicio
