### ISSUE TITLE
formao PDF Daily Handy Washing Inspection 

### ISSUE THREAD

**Issue by delcabo** [caom92/Espresso#192]
el PDF esta in poquito desfigurado... tal vez in ajustito

![image](https://cloud.githubusercontent.com/assets/28766240/26326363/b202771c-3eef-11e7-93a0-7bd9c3c82856.png)

**Comment by caom92** [comment]
Ya esta arreglado, solo falta subirlo al servidor de Julio

**Comment by VMiracle** [comment]
Este bug fix ya fue subido al git, procedo a cerrar el problema

**Comment by delcabo** [comment]
gracias espero cuando me digan para revisarlo con Wilma...

**Comment by delcabo** [comment]
Buen dia!!!

Pregunta!! el cerrar significa que esta para Ustedes o hasta el usuario final....???

porque todavia sale mal el format!

saludos

**Comment by caom92** [comment]
Significa que el problema fue resuelto, no necesariamente significa que ya esta disponible para el usuario final. Este sitio se usa para rastrear trabajo que tengamos pendiente. Cuando ese trabajo esta terminado, lo cerramos para indicar de que hemos concluido con esa tarea. Muchas de estas tareas ya estan corregidas, pero aún no se suben a su servidor. Yo le avisaré cuando hayamos hecho esto. Debe ser paciente.
