### ISSUE TITLE
NOUCA  no encabezados de campos

### ISSUE THREAD

**Issue by delcabo** [caom92/Espresso#195]
Hola asi salio la pantalla de NOUCA
![image](https://cloud.githubusercontent.com/assets/28766240/26374510/6795cf28-3fba-11e7-9805-a43b4fc81236.png)

**Comment by delcabo** [comment]
aaah tal vez es mi CAche...  porque no salio los encabezados en otra bitacora tambien!!  la limpiare

**Comment by delcabo** [comment]
Solo Productos y Area si puede ser campos abiertos y quedara listo!!

**Comment by delcabo** [comment]
uppps algunos mensajesss....   Creen que el campo de Corrective Actions puede ser tipo BOX como este que estoy escribiendo,, que se puede dar "Enter" rayar lineas "_________________"

**Comment by delcabo** [comment]
o hasta meter imagines jijijijijjii

ahorita me salio estos mensajes, tal vez algunos estan limitados de cantidad de texto o tamano

![image](https://cloud.githubusercontent.com/assets/28766240/26375042/4244e202-3fbc-11e7-8114-0513fa897d53.png)

**Comment by delcabo** [comment]
tambien anexar la fecha, antes de la hora!! puede ser que esto sea de dias pasados !!

**Comment by caom92** [comment]
Ya estamos trabajando en lo de los errores, en cuanto a que las acciones correctivas sea un campo seleccionable, necesitamos saber cuales van a ser las opciones.

**Comment by caom92** [comment]
Estaba revisando los problemas que menciona, uno es debido al campo del area porque no habia campos de area capturados en la BD, al final decidimos dejar ese campo abierto, entonces ese problema ya no va a pasar. El otro problema es con el campo que dice "Description", el cual solo permite 128 caracteres máximo. Lo que usted escribió es más largo que eso. De todas formas ya extendimos el limite de caracteres.

**Comment by caom92** [comment]
Al subir estos cambios al servidor de Julio, no hay que olvidar modificar la tabla de la BD
