### ISSUE TITLE
En NUOCA, se debe anexar un campo de fecha

### ISSUE THREAD

**Issue by caom92** [caom92/Espresso#198]
Debido a que Julio dice que en aquí se pueden reportar sucesos de días anteriores, habrá que agregar otro campo de fecha que indique la fecha en que ocurrió el incidente reportado. Este se llamará incident_date. Yo me encargo de modificar los servicios del backend y la BD.

**Comment by caom92** [comment]
No olvides anexar el campo en la pantalla de reporte y en el PDF también

**Comment by delcabo** [comment]
Buen dia solo seguimiento... 

todavia campo AREA y PRODUCTO no es campo abierto, 
DESCRIPTION & CORRECTIVE ACTION a 128 caracteres
cuando quieres SAVE 

Mensaje de YOU MUST SELEC CORRECTIVE ACTION OTHER THAN NONE  
y luego "Input argument area_id is undefined"

![image](https://cloud.githubusercontent.com/assets/28766240/26458908/8cc2923e-4129-11e7-8d05-9cd2975f340c.png)

**Comment by caom92** [comment]
Esos problemas ya fueron mencionados en #195 , los cambios ya se hicieron pero aún no se suben al servidor. Espere a que los hayamos subido y vuelva a probar.
