### ISSUE TITLE
ATP  que sean campos abiertos...

### ISSUE THREAD

**Issue by delcabo** [caom92/Espresso#200]
Buen dia Ijole 
haber como explico... que no se use las areaas y items, solo poner 1 registro abierto y in '+'  SI se hace otro registro...

tal vez ya lo tienen contemplado asi..

**Comment by caom92** [comment]
Acabamos de hacer modificaciones en esa bitacora, pero aún no lo subimos al servidor. Espere a probar estos cambios y luego nos dice qué piensa.
