### ISSUE TITLE
NOUCA  no me deja poner fecha anteriores...

### ISSUE THREAD

**Issue by delcabo** [caom92/Espresso#203]
hola  podra dejar capturer fechas Viejas y dejar los campos de "Descripcion, Corrective Action" tipo Memo o algo asi sin limite de escritura, como si fuera in cuadro en vez de linea!! para poder ir viendo lo que escriben...  este ejercicio que se muestra es de los mas pequenos de tanta informacion que escriben cada area a veces...  (algo parecido a este cuadrito donde estoy escribiendo :) )  y hasta deja meter imagenes!!!
que elegancia!!!!

![image](https://cloud.githubusercontent.com/assets/28766240/26501893/b40f7e62-41ef-11e7-9e38-ee4d0af0aab5.png)
![image](https://cloud.githubusercontent.com/assets/28766240/26502109/5c3d277e-41f0-11e7-9f8e-541b0d8eccea.png)

**Comment by caom92** [comment]
El campo de fecha estaba configurado para que sólo se pudieran ingresar fechas desde el día de hoy en adelante. Ya fue corregido y el cambio se veerá reflejado en la próxima actualización.
