### ISSUE TITLE
Finish Poduct chceck

### ISSUE THREAD

**Issue by delcabo** [caom92/Espresso#204]
Hola me envoi in mensaje al darle ENVIAR  y no sale en los reportes nada todavia!

![image](https://cloud.githubusercontent.com/assets/28766240/26502391/8b6f8766-41f1-11e7-91a4-8c64f4797640.png)

**Comment by caom92** [comment]
El problema es que el campo de cliente esta limitado para que ingrese texto que tengan un mínimo de 3 caracteres, pero ud. ingresó "TJ" que tiene 2 caracteres y debido a eso la bitacora fue rechazada. Ya redujimos el límite y el cambio se veerá reflejado en la próxima actualización.
