### ISSUE TITLE
ATP

### ISSUE THREAD

**Issue by delcabo** [caom92/Espresso#205]
Hola 
La pagina de ATP no salen el area de captura todavia!

![image](https://cloud.githubusercontent.com/assets/28766240/26503612/34f58cf0-41f6-11e7-8260-d4672c5e73f1.png)

**Comment by caom92** [comment]
Para ATP el supervisor debe capturar las áreas. La diferencia es que ahora ATP tiene su propia tabla para sus propias áreas. Antes usaba las mismas áreas que el PreOp.

**Comment by delcabo** [comment]
Hola, pero en el ATP no se sabe donde se haran las pruebas, cada vez...  por eso al final pedi si puede ser campo abierto igualito a de Finish Produc check..  algo parecido!!

puedes ser mesa, pared, piso, manos, lampara   nose infinidad..

**Comment by delcabo** [comment]
Revisare con todo el equipo para usarlo asi, ha exepcion que me digas que se ajjustara.........

**Comment by caom92** [comment]
La bitácora de ejemplo que nos había dado tenían claramente sus propias áreas que de hecho eran muy similares a las de PreOp, por eso habíamos decidido conectar las áreas de esta bitacora a las de PreOp

**Comment by caom92** [comment]
Pase las tareas relacionadas con este problema a #218
