### ISSUE TITLE
Modificaciones en servicios para Autorizaciones y Update

### ISSUE THREAD

**Issue by VMiracle** [caom92/Espresso#210]
Para finished product, el servicio de authorization-report, además de la información que regresa, necesito que regrese otro atributo a la altura de entries que sea log_info, donde vendría lo mismo que contiene log_info del servicio de log-gmp-packing-finished product.

Para authorization-report de Unusual occurrence necesitaré lo mismo, un log_info que (al menos de momento) me regrese los turnos, además de la información que ya trae.

**Comment by caom92** [comment]
Para authorization-report de finished product, este ahora retorna un campo llamado items, adentro se encuentran los campos entries y log_info que ocupas. En unusual occurrence hice lo mismo, el arreglo se llama items y en el esta entry y shifts. Lo tuve que hacer así porque la función que me crea el servicio nomás me permite retornar 1 variable, de lo contrario hubiera tenido que escribir todo el servicio manualmente.
