### ISSUE TITLE
Convertir NUOCA en una bitacora disponible para todos los programas 

### ISSUE THREAD

**Issue by caom92** [caom92/Espresso#217]
Julio quiere que NUOCA pueda estar disponible para todos los programas en todas las áreas. Hay 2 maneras de poder hacer esto:

1. Agregar una bitacora NUOCA específica para cada programa, así podrá quedar relacionada con el inventario correcto en la BD. Esto tendrá la ventaja de que la bitacora respetará adecuadamente la relación de privilegios entre bitacora - usuario que hemos construido en el sistema. La desventaja sería que si en dado caso quisieran generar un reporte con todos los NUOCA en una sola fecha, sería un poco más complicado porque la BD tendría que buscar en varias tablas de NUOCA dispersas entre los diferentes programas.
2. Mover NUOCA a un programa general que esté disponible desde el principio para todos los usuarios. Esto ofrecerá la capacidad de poder hacer búsquedas en todos los NUOCA visitando solamente 1 tabla en la BD. La desventaja es que habrá que buscar una manera de cómo guardar en dicha tabla los IDs de los renglones de cualquier tabla en la BD. Julio sugirió que fueran campos de texto, pero hacerlo así rompe todo el esquema en el que hemos trabajado y de hecho pone en duda la necesidad de haber invertido tanto tiempo y esfuerzo en construir una BD.

**Comment by delcabo** [comment]
Buen dia y tambien si el campo Corrective Action puede ser tipo MEMO, que no este limitado, como si fuera in Text editor...

es mas hasta fotos que se pongan.... se puede???

**Comment by caom92** [comment]
NUOCA ya tiene un campo donde pueden agregar el enlace para el album en Picasa

**Comment by delcabo** [comment]
si lo vi Carlos, pero muchos toman bastante texto para esto, y a veces menos fotos o documentos que puedan agregar a picassa.   

Dime por favor si es possible meter este campo de Accion Correctiva como Memo Type??

**Comment by caom92** [comment]
Ahí contestaré sus dudas.
