### ISSUE TITLE
Approvals     

### ISSUE THREAD

**Issue by delcabo** [caom92/Espresso#219]
Hola me envia al iniciar las aprovaciones "Some Error" al inicio
![image](https://cloud.githubusercontent.com/assets/28766240/26562704/9168c2de-447d-11e7-86e6-32d697d3be1b.png)

**Comment by caom92** [comment]
Era un error con los permisos, al parecer alguien le había quitado los permisos a Yaneth para la bitacora de PreOp desde el administrador. Ya se los cambié y debería poder usar esa pantalla correctamente ahora.

**Comment by delcabo** [comment]
Ijole sabes siguen saliendo las mismas 127 logs...  :(

**Comment by delcabo** [comment]
en el caso de Yaneth

**Comment by caom92** [comment]
El problema parece ser el mismo descrito en #220
