### ISSUE TITLE
Sacale Calibration -  Inventory

### ISSUE THREAD

**Issue by delcabo** [caom92/Espresso#221]
Hola buen dia

Extrano cuando doy de baja in item.. al volver a entrar vuele a salir...

igual en USERS -Administrador, inactive a Zahid varias veces y vuelve a salir

![image](https://cloud.githubusercontent.com/assets/28766240/26599332/1b1e596c-452d-11e7-88ab-510f091c5175.png)

**Comment by caom92** [comment]
Resulta que este error se propaga a otras bitacoras. Ya estamos trabajando en ello.

**Comment by caom92** [comment]
Ya quedó arreglado, debería funcionar ahora.
