### ISSUE TITLE
Pest Control - Report 

### ISSUE THREAD

**Issue by delcabo** [caom92/Espresso#224]
Hola con el use de JULIO... quise ver algunos reportes de pest control y al momento de cambiar de Zona me dice Error, me cambia a reporte Preoperativos y me da el mismo mensaje ...

![image](https://cloud.githubusercontent.com/assets/28766240/26639426/a6151a22-45d9-11e7-86a7-8cf30ccacaac.png)

**Comment by caom92** [comment]
No pude replicar el problema, a mi me funciona bien, hay alguna otra cosa que hizo? Ya probó borrando el caché del navegador? Tuve que cambiar la contraseña a la misma que tienen todos los otros usuarios para poder tener acceso a su cuenta e intentar replicar el problema para ver qué mensajes de error me envía.

**Comment by delcabo** [comment]
OK Carlos, borrare de Nuevo cache, e intentare de Nuevo

**Comment by delcabo** [comment]
gracias Carlitos ya funciono!!!
