### ISSUE TITLE
ATP  encabezado

### ISSUE THREAD

**Issue by delcabo** [caom92/Espresso#225]
Hola el encabezado de Inventario de ATP dice que es de  Finished Product
![image](https://cloud.githubusercontent.com/assets/28766240/26646312/f3fd8010-45ef-11e7-9f1a-58b61022dd7d.png)

**Comment by delcabo** [comment]
revisando la captura de ATP, lo unico que veo que podra ser possible es anexar otro campo texto, donde pongamos lo que sea (ITEM) intente ponerlo en el campo "test" la mesa y el resultado junto pero no me dejo capturer, solo es numerico  creo!!  eje "#18 - 3"  donde #18 es la mesa y el 3 es el resultado de lectura del aparato ATP...
![image](https://cloud.githubusercontent.com/assets/28766240/26646986/a5ad7a7a-45f2-11e7-979e-f246a4da416b.png)

**Comment by delcabo** [comment]
y que no ponga candados, porque no todas las areas se hacen diarias.... algunas son 2 veces por semana.. etc

**Comment by caom92** [comment]
No sugiero que use ATP ahorita, porque tenemos planeados hacerle muchos cambios ahorita; como está el ATP en estos momentos no refleja cómo estará en el futuro. Sin embargo no hemos subido ningún cambio aún proque ATP no tiene prioridad para nosotros ahorita porque estamos trabajando en las autorizaciones de Finished Product y NUOCA

**Comment by caom92** [comment]
Le sugiero que espere a que hayamos subido cambios y luego intente usarlo.
