### ISSUE TITLE
Pre Oeprativo

### ISSUE THREAD

**Issue by delcabo** [caom92/Espresso#226]
Hola buenas tardes

Cuando se usa en ingles usamos W R S, pero cuando usamos a Espanol, podemos hacer el ajuste a que Cambie el valor a L E D ?
y en la parte baja del PDF que diga

"Notes: RC=Recleaned   WRS=Wash/Rinse/Sanitize (Ozone Water)
  Notas: LED=Lavado/Enjuagado/Desinfectado"

y ojala pronto la firma

:)

**Comment by caom92** [comment]
Sí se puede hacer, pero al igual que lo de la firma, quedará para otro contrato porque ese cambio implicará modificar muchas cosas de como funcionan ahorita.

**Comment by caom92** [comment]
Esto ya quedo con los cambios mas recientes.
