### ISSUE TITLE
manage inventory SCALE CALIBRATION

### ISSUE THREAD

**Issue by delcabo** [caom92/Espresso#229]
Hola buenas tardes

al momento  de querer dar de baja, dice que SI a todo muy bonito pero no lo quita finalmente...
y cuando queremos mover registro de arriba hacia abajo o visceversa no lo respeta...

![image](https://cloud.githubusercontent.com/assets/28766240/26801329/60d50a46-49f1-11e7-9ab3-bd06b9e385e6.png)

**Comment by VMiracle** [comment]
La versión actual en el servidor ya debería estar funcionando correctamente. De no ser así, con su aviso lo revisaré nuevamente

**Comment by delcabo** [comment]
Hola buenas tardes

Probamos de Nuevo la revision y nada, todavia no borra o bloquea items
y cuando movemos de lugar algun item, no respeta se vuelve a poner en el nivel original...

**Comment by caom92** [comment]
Parece que algo salió mal cuando subíamos actualizaciones a su servidor porque varios archivos no habían sido actualizados. Como sea, este problema ya debio ser resuelto.

**Comment by delcabo** [comment]
ijole
ya casi terminaba de prender todos los campos de Nuevo.   iba etapa x etapa
y a lo ultimo 
se apagaron todos de Nuevo..... :(  llevo 3 veces hacienda!!! jijijij
![image](https://user-images.githubusercontent.com/28766240/26995689-e634332c-4d22-11e7-996c-54f48c55a02e.png)

**Comment by delcabo** [comment]
hold it!

ya aparecieron bien... 
solo que el "Inventario Gage Calabaza Dura" cebolla no me deja subirla

**Comment by caom92** [comment]
yo lo acabo de agregar sin ningún problema

**Comment by caom92** [comment]
Igual estaba revisando y encontré un error que provocaba que se desactivaran todas las básculas, ya subí la corrección al servidor y ya no debería ocurrir
