### ISSUE TITLE
Finish Product Check

### ISSUE THREAD

**Issue by delcabo** [caom92/Espresso#244]
Hola 

Acabamos de capturer una prueba para esta bitacora, pero al momento de abrirla en Revision o aprbacion no abre la bitacora... 

![image](https://user-images.githubusercontent.com/28766240/26849490-3b1107f6-4ab9-11e7-96ac-4fd7136f52ac.png)

**Comment by caom92** [comment]
No pudimos reproducirlo en nuestra versión del programa, intente refrescar el caché y si aún así no funciona, espere a la próxima actualización del sistema y vuelva a intentar.

**Comment by delcabo** [comment]
Hola buenas tardes
:( no da los encabezados para esta pantalla  algo raro   use el usario de CINTYA

![image](https://user-images.githubusercontent.com/28766240/26897366-2c564982-4b7d-11e7-8537-349fd86b4f3a.png)

**Comment by delcabo** [comment]
en la aprobacion ya quedo muy bien  gracias!!

Solo falta en la captura

**Comment by VMiracle** [comment]
Acabo de subir la corrección para que la captura funcione adecuadamente

**Comment by delcabo** [comment]
Buen dia!!  Creo que el campo batch es solo numeric???, so es asi, puede ser abiero Alfanumerico por fas

![image](https://user-images.githubusercontent.com/28766240/27044508-a1bc5a8a-4f52-11e7-9d51-9b979ea55d04.png)

**Comment by delcabo** [comment]
Nota, en muchas ocaciones no Habra necesidad de escribir NADA en las Notes o Comentarios, y al parecer tiene candado.. favor de quitarlo

**Comment by caom92** [comment]
Ya arreglamos esos detalles que menciono y ya estan arriba en el servidor.

**Comment by delcabo** [comment]
probamos pero manda otro mensaje
![image](https://user-images.githubusercontent.com/28766240/27053805-85d25c90-4f73-11e7-89b6-b0cf823944c8.png)
