### ISSUE TITLE
Glass & Britlle BCN-WILMA

### ISSUE THREAD

**Issue by delcabo** [caom92/Espresso#245]
extrano no me da nada cuando quiero dar de alta Nuevo ITEMs en esta bitacora... si me dejo dar las Areas.

![image](https://user-images.githubusercontent.com/28766240/26849775-3c322416-4aba-11e7-90c6-66de7e1f2660.png)

**Comment by caom92** [comment]
@VMiracle resolvió este problema, espere a la próxima actualización
