### ISSUE TITLE
NOUCA

### ISSUE THREAD

**Issue by delcabo** [caom92/Espresso#246]
Hola

la pagina de NOUCA no  abre compeltamente (ni el SOP ni la captura)  ya se borro el cache varias veces

![image](https://user-images.githubusercontent.com/28766240/26899294-8bdbd2cc-4b83-11e7-9fa1-a446dd876305.png)

**Comment by VMiracle** [comment]
Acabo de arreglar el despliegue y este arreglo ya se ve reflejado en el servidor, mantengo este hilo abierto por si hubiera algún problema durante la captura
