### ISSUE TITLE
Aprobaciones  FANTASMASSSS

### ISSUE THREAD

**Issue by delcabo** [caom92/Espresso#247]
Hola, no estoy seguro todavia si es a todos

pero a algunos usuarios todavia les da 2 aprobaciones pendientes, pero no tienen ningun registro visible..

en la caso de Yaneth, si salen 2

Saludos

**Comment by caom92** [comment]
Era un error de cómo contaba el servidor las bitácoras no autorizadas, ya fue corregido y ya se ve reflejado en el servidor
