### ISSUE TITLE
Contador de aprobaciones pendietes NO sale

### ISSUE THREAD

**Issue by delcabo** [caom92/Espresso#248]
Hola bune dia!

algo extrano, pense que saldria despues.. pero nada.. el Contador no sale desde hace unos dias..
![image](https://user-images.githubusercontent.com/28766240/27042255-3d1f0f02-4f4b-11e7-83c2-4bb9af1f1427.png)

**Comment by caom92** [comment]
Ya arregle el problema, en unos momentos lo subire al servidor
