### ISSUE TITLE
ATP screen lectura 0

### ISSUE THREAD

**Issue by delcabo** [caom92/Espresso#249]
Hola buen dia!
no estoy seguro pero envoi in mensaje despues de aceptar los datos
si dijo bitacora envia
pero tal vez porque tengo valores de 0, que si es acceptable.. en muchos casos 
![image](https://user-images.githubusercontent.com/28766240/27043031-a69d7034-4f4d-11e7-8178-11e75eaf5d78.png)

**Comment by delcabo** [comment]
DAto  extrano!!!    le cambie el valor a "1" para probar y dio este mensaje

![image](https://user-images.githubusercontent.com/28766240/27043135-00cd9c14-4f4e-11e7-9304-e0f34bd9b41c.png)

**Comment by caom92** [comment]
Ya subi las correcciones para estos 2 errores
