### ISSUE TITLE
No cambia de HEADERS cuando cambio de panatalla

### ISSUE THREAD

**Issue by delcabo** [caom92/Espresso#250]
Hola buen dia

No cambia de encabezado cuaundo cambie de ATP a Pest Control... sigue saliendo ATP!
![image](https://user-images.githubusercontent.com/28766240/27046326-d997d442-4f58-11e7-825a-f798c359e5d2.png)

**Comment by VMiracle** [comment]
Buenas tardes, ya se encuentra resuelto y disponible en el servidor
