### ISSUE TITLE
Aprobaciones

### ISSUE THREAD

**Issue by delcabo** [caom92/Espresso#252]
No salva las aprobaciones, y creemos que no guarda los cambios, segun las ultimas pruebas...!

Esta limitado el BATCH a alguna cantidad de digitos.. ??

![image](https://user-images.githubusercontent.com/28766240/27055118-36e8738a-4f78-11e7-9c96-258b0a93417d.png)

**Comment by caom92** [comment]
@VMiracle hizo algunos ajustes y ya debería estar funcionando el campo de Batch adecuadamente.
