### ISSUE TITLE
Director swith zones

### ISSUE THREAD

**Issue by delcabo** [caom92/Espresso#253]
Buenas ttardes

cuando consultas regisstros y cmbias a zona con las mismas fecha no cambia de zona el reporte!

![image](https://user-images.githubusercontent.com/28766240/27104801-289bc848-5042-11e7-9106-88e7af2183b3.png)

**Comment by caom92** [comment]
Tiene que volver a hacer clic en el boton Open Report, si solo cambia la zona, no se van a modificar los reportes automaticamente.

**Comment by caom92** [comment]
Le sugiero que no cambie la contraseña de su cuenta, eso previene que podamos hacer pruebas en su servidor. Si desea poner una contraseña diferente, entonces haganoslo saber para poder acceder al sistema. Le recuerdo que el sistema aun esta en desarrollo, no es un sistema listo para producción, por lo que es importante que nosotros tengamos la libertad de hacer las pruebas y modificaciones necesarias.
