### ISSUE TITLE
Finish Product

### ISSUE THREAD

**Issue by delcabo** [caom92/Espresso#254]
Buenas tardes

no salen registros para consulto a nivel Director  (o Julio) 
![image](https://user-images.githubusercontent.com/28766240/27108511-78e7cd28-5052-11e7-996d-922c19f4ba6b.png)

**Comment by caom92** [comment]
Acabo de probar en su servidor y a mí sí  me salen para BCN, intente borrar la memoria caché y pruebe de nuevo.

![screenshot_2017-06-14_12-02-04](https://user-images.githubusercontent.com/9997614/27149712-4fa2fa6c-50f9-11e7-865a-de68a8e85ae0.png)

**Comment by delcabo** [comment]
Works!!!! 
Muchas gracias
