### ISSUE TITLE
Daily Scale Calibration  Yaneth

### ISSUE THREAD

**Issue by delcabo** [caom92/Espresso#255]
Buenas tardes al parcer no modifica cambios en los reigstros de numerous, pero si en las notas y observaciones.
![image](https://user-images.githubusercontent.com/28766240/27109909-96badc48-505a-11e7-9453-ba0cb95e2c45.png)

![image](https://user-images.githubusercontent.com/28766240/27109899-8531083a-505a-11e7-8d2e-f4b2fd63be58.png)

**Comment by caom92** [comment]
Era un error en el servidor, ya lo corregí, debería estar funcionando.
