### ISSUE TITLE
Bitacoras termometros-basculas etc..

### ISSUE THREAD

**Issue by delcabo** [caom92/Espresso#259]
Buen tardes
Podemos poner campo abierto Alfanumerico a estas bitacoras y cambiar la etiqueta que diga "Prueba" por "Lectura" & "Reading"
por favor 

![image](https://user-images.githubusercontent.com/28766240/27303717-8d78c1c8-54f0-11e7-8ddb-2f55a65131db.png)

saludos!

**Comment by VMiracle** [comment]
Ya está en el servidor, pero para verlo reflejado es posible que tengan que cerrar y volver a abrir sesión y/o borrar la caché.

Saludos

**Comment by delcabo** [comment]
oK GRACIAS
Borre Cache y volvi a entrar
pero me da
![image](https://user-images.githubusercontent.com/28766240/27309948-b7ea56f4-550b-11e7-8feb-081fbcfea2c4.png)

**Comment by delcabo** [comment]
Nice!" pone en rojo lo que no es acceptable!!!

**Comment by delcabo** [comment]
No funciona todavia????  :(
"The result must be a number"
