### ISSUE TITLE
Termometros Log ADD FIELD

### ISSUE THREAD

**Issue by delcabo** [caom92/Espresso#260]
Hola buenas tardes

revisando como BCN y LAW-SSF hacen esta bitacora.. se revise lo siguiente

Se require adehir in campo mas "Sanitized/Sanitizado" con opcion de =  si o no

![image](https://user-images.githubusercontent.com/28766240/27305092-2abc6936-54f5-11e7-9243-6d28a5abba34.png)

**Comment by caom92** [comment]
Ya agregamos ese campo con los cambios más recientes
