### ISSUE TITLE
consulta e impresion de LOG de Basculas

### ISSUE THREAD

**Issue by delcabo** [caom92/Espresso#261]
Buenas tardes

revisar el orden de apariencia cuando se abren las bitacoras en la aprobacion
consulta de reporte y pdf.

No aparecen segun el orden de inventario ajustado..

![image](https://user-images.githubusercontent.com/28766240/27306148-6a40e024-54f9-11e7-8197-9e204d708372.png)

saludos

**Comment by VMiracle** [comment]
Hola, ¿esto es en todas las bitácoras o en algunas en específico?

Saludos

**Comment by delcabo** [comment]
Buena pregunta apenas probamos esta, como todavia no llegamos a la parte de revisar las PDF..

**Comment by caom92** [comment]
Según esto, ya lo ajustamos, intente probar de nuevo para ver si ya aparecen en el orden que espera.

**Comment by delcabo** [comment]
Listo funciona bien la impresion! gracias!
