### ISSUE TITLE
Cambiar funcionamiento de la pantalla de captura ATP

### ISSUE THREAD

**Issue by caom92** [caom92/Espresso#262]
Julio me comentó que la pantalla de captura de ATP no era suficientemente clara para los usuarios a la hora de agregar objetos a la lista de pruebas. Yo le propuse 2 cambios: 

1. Mover el cuadro donde se seleccionan objetos para agregarlos a la lista al tope de la pantalla, antes de la lista, en lugar de que estuviera al fondo después de la lista
2. En lugar de que sea una caja de selección, que sea una caja de texto donde despliegue como sugerencias los objetos que ya estén capturados en el inventario, similar a como lo hicimos con NUOCA

**Comment by delcabo** [comment]
Hola, este ajuste ya esta arriba 
en el servidor?

**Comment by VMiracle** [comment]
Aún no se encuentra en el servidor
