### ISSUE TITLE
dejo de arrojar datos en los reportes

### ISSUE THREAD

**Issue by delcabo** [caom92/Espresso#263]
Buen dia!

Carlos/Victor no se porque, pero esta seccion de reportes JULIO estaba funcionando de maravilla hace unos minutos (inclusive cambie de zona) y despues de 3-4 consultas ya no quiso darme nada!! 

![image](https://user-images.githubusercontent.com/28766240/27391920-1284dc66-565a-11e7-8a60-c7cff6b2dd27.png)
![image](https://user-images.githubusercontent.com/28766240/27392035-60f60e1a-565a-11e7-9181-b8ffb651ae14.png)

**Comment by delcabo** [comment]
Y por favor si puede ponerse el HEADER o encabezado de la opcion que estoy presente!!

**Comment by caom92** [comment]
No se que era, pero ya funciona.
