### ISSUE TITLE
View Manuals

### ISSUE THREAD

**Issue by delcabo** [caom92/Espresso#264]
Hola hace un momento subi un manual "Glass & Britlle" en BCN zone  (Subio perfectamente) segun el mensaje... y rapido

pero todavia no aparece, me cambie de opciones, sali y entre
etc....

pero sale el chicke, chicken chicken...

![image](https://user-images.githubusercontent.com/28766240/27395018-27a243b4-5663-11e7-8efa-bcb73eb16411.png)

**Comment by caom92** [comment]
Es por el cache, tiene que borrarlo para que se despliegue el correcto.
