### ISSUE TITLE
Cotizar por favor

### ISSUE THREAD

**Issue by delcabo** [caom92/Espresso#301]
Buenas tardes tengo algo para cotizar!!!
tal vez cae en nivel 2 o 3
![image](https://user-images.githubusercontent.com/28766240/28186544-70e0f146-67d0-11e7-8cdc-94bf0221e813.png)

**Comment by delcabo** [comment]
![image](https://user-images.githubusercontent.com/28766240/28186553-796abbe4-67d0-11e7-8eeb-5ec076061d8b.png)

**Comment by delcabo** [comment]
![image](https://user-images.githubusercontent.com/28766240/28186593-a6ee16d8-67d0-11e7-823e-fe902c32af29.png)

**Comment by delcabo** [comment]
la idea es que cada zona puede hacer sus inventarios de bitacoras (Nomenclatura y nombre de la bitacora)  solamente y el que captura que puede seleccionar una bitacora del combo de inventarios, luego in campo de datos (texto largo por favor), campo de link, y que puede subir 2 fotos, de camara o de archive)
andales a ver, digan algo!! ehhh

**Comment by VMiracle** [comment]
Ok, Julio, ya lo vi y creo que me espanté por nada

Entraría dentro de Tier 2 + Campo para subir imágenes (no se necesita de dos campos, en un solo campo se pueden subir varias). De momento se limitaría a mostrar todas las imágenes en un reporte, una tras otra

El costo como marca el documento que ya mandamos sería de 4000.00 (3500.00 por tier 2 y 500.00 por agregarle campo de imagenes)

Solo tenemos una pregunta, ¿esta bitácora sería para empezar a desarrollarla desde ya?

**Comment by delcabo** [comment]
Hola!!! perfecto si desde ya... solo les enviare la Orden de compra!!!

La solicitio de una vez!

**Comment by VMiracle** [comment]
Ok, enterados

**Comment by delcabo** [comment]
a que correo enviamos la orden?
Carlos?

**Comment by delcabo** [comment]
y al nombre del proveedor?

**Comment by VMiracle** [comment]
Otra pregunta, Julio

Carlos me dice que esta bitácora será para GMP y Packing, pero que sería para un nuevo modulo y naturalmente la bitácora tendrá su propio nombre, en cuanto lo sepa nos avisa para tener los mismos nombres en el sistema
