### ISSUE TITLE
Ordenar áreas del inventario por orden alfabético

### ISSUE THREAD

**Issue by caom92** [caom92/Espresso#341]
En la pantalla de administrar áreas, éstas deben aparecer listadas por órden alfabético

![imgpsh_fullsize 1](https://user-images.githubusercontent.com/9997614/29888937-643e4ad4-8d77-11e7-92b1-368eb4ff04c0.png)

**Comment by caom92** [comment]
En la imágen que nos pasó, es una captura de Glass & Brittle Plastic Inspection, ¿desea que el inventario se ordene por orden alfabético en esta bitácora únicamente o quiere que ese cambio se aplique a todas las bitacoras del sistema de una vez?

**Comment by delcabo** [comment]
Hola, bueno cierto, seria lo ideal en todas....

gracias

**Comment by caom92** [comment]
En todas será

**Comment by caom92** [comment]
Ya se deben listar las áreas en orden alfabético en su servidor.
[Tiempo total: 1 hora]
