### ISSUE TITLE
Dar de baja áreas del inventario

### ISSUE THREAD

**Issue by caom92** [caom92/Espresso#342]
Se deben de dar de baja aquellas áreas que estén repetidas o que no pertenezcan a esa bitácora.

![imgpsh_fullsize 1](https://user-images.githubusercontent.com/9997614/29889129-eeb28964-8d77-11e7-8132-8046b27f9828.png)

**Comment by caom92** [comment]
De nuevo, la fotocaptura que nos envió sólamente muestra el Glass & Brittle Plastic Inspection, podemos nosotros borrar desde la base de datos las áreas que están de más o podemos hacerle una pantalla donde el supervisor pueda borrar esas áreas para que no tengan que estar dependiendo de nosotros. ¿Cuál de estas dos opciones prefiere? Si quiere que le escribamos una pantalla al supervisor para borrar las áreas, ¿quiere que sea únicamente para el Glass & Brittle Plastic Inspection o se lo agregamos a todas las bitácoras de una vez?

**Comment by delcabo** [comment]
los 2
Lo mas facil es borrarlas ahorita
pero lo ideal es que el sistema tenga la opcion ABC en todos las secciones

Saludos

**Comment by caom92** [comment]
Implementaremos las pantallas entonces

**Comment by caom92** [comment]
@VMiracle y yo hemos estado analizando el problema y encontramos una mejor solución que implica menos trabajo de desarrollo en implementarla. En lugar de ofrecer una pantalla donde se dén de baja las áreas, podemos agregar una condición al momento de capturar áreas nuevas para que no se puedan dar de alta áreas con nombres repetidos y agregaremos también la opción de editar los nombres de las áreas capturadas para mayor conveniencia.

**Comment by delcabo** [comment]
Pos mas elegante aun! :)

sale!

**Comment by caom92** [comment]
[Tiempo total backend: 1 hora]

**Comment by VMiracle** [comment]
Acumulado al lunes 4 de sept [7 horas]

**Comment by VMiracle** [comment]
Total: 10 Horas
