### ISSUE TITLE
Document Control - Ajustar el tamaño de la imágen para que cubra toda la hoja

### ISSUE THREAD

**Issue by caom92** [caom92/Espresso#343]
En el reporte PDF de Document Control, las imágenes agregadas se ven más chicas que el tamaño de la hoja. Julio preferiría que se viera más grande para que se apreciaran los detalles. 

![imgpsh_fullsize 2](https://user-images.githubusercontent.com/9997614/29889431-fe97f6ec-8d78-11e7-8162-6577de601a78.png)

**Comment by caom92** [comment]
@VMiracle  estuvo buscando alternativas para resolver este problema y llegó a la conclusión de que la solución más corta era desplegar primero en una página el recuadro chico donde viene la información de esa entrada, pasar a una hoja nueva y empezar a desplegar todas las imágenes del tamaño de la hoja completa. Luego volver a mostrar el recuadro de la siguiente entrada y repetir sucesivamente. Se va a gastar más papél así, porque por cada imágen se usará 1 hoja y para los registros aunque es un recuadro de 3 renglones solamente, se va desplegar 1 recuadro en toda la página también. Pero es la única forma de desplegar las imágenes del tamaño que desea sin romper toda la demás funcionalidad y sin dedicarle demasiado tiempo de desarrollo. ¿Esta de acuerdo con esta solución?

**Comment by delcabo** [comment]
Si, de acuerdo..  la intencion es solo imprmir unas 3 muestras en cada auditoria, 
al final la mayoria se revisarian por pantalla...

ahi es donde debe poder darle click a la foto o boton para abrirla y poder hacerle zoom

**Comment by caom92** [comment]
Le dire a @VMiracle  que lo implemente así entonces. Lo de que se le pueda hacer clic a la foto para verla en otro programa no se puede porque no depende de la programación de nosotros, depende del navegador. Tal vez exista algún plug-in o un add-on para su navegador que le permita hacer lo que quiere, pero es cosa de cada usuario buscarlo e instalarlo. Lo más que puede hacer es hacerle clic derecho a la imagen (o tocar la imagen y mantener presionada la pantalla por un instante, si está en un dispositivo móvil) y en el menú que le aparece hacer clic donde diga "Guardar imágen", esto la guardará en su computadora (o dispositivo móvil) y así ya podrá abrir la imágen con el programa que usted desee.

**Comment by caom92** [comment]
[Total de tiempo de desarrollo: 3 horas]

**Comment by caom92** [comment]
Ya está implementado, faltará subirlo al servidor de @delcabo
