### ISSUE TITLE
Document Control - Los reportes deben desplegarse con la fecha de registro no fecha de captura

### ISSUE THREAD

**Issue by caom92** [caom92/Espresso#344]
En la pantalla de solicitar reportes, donde el usuario ingresa un intervalo de fechas, la fecha desplegada en la lista de resultados de búsqueda debe ser la fecha en la que se registro la bitácora que fue registrada en el reporte, no la fecha en la que fue capturado el reporte. 

![imgpsh_fullsize 3](https://user-images.githubusercontent.com/9997614/29889690-f6573122-8d79-11e7-954a-c3dca75b9fce.png)

**Comment by caom92** [comment]
Este es un cambio muy complicado de realizar debido a que esa pantalla es general a todas las bitácoras del sistema, cualquier modificación que se le haga a esa pantalla afectará a todas las demás bitácoras del sistema a menos que hagas una desacople y manejemos la pantalla de reporte del Document Control como un caso especial, lo cuál implicará mucho tiempo de desarrollo. Pero es posible.

El verdadero problema es con la forma en la que fue diseñado el Document Control. En esta bitácora, el usuario puede registrar varios documentos a la vez, no solamente 1 y cada uno de los documentos ingresados puede potencialmente tener una fecha de registro diferente a la que tienen los otros documentos que van a ser registrados. Debido a esto no podemos simplemente desplegar 1 "fecha de registro" porque cada bitacora puede tener muchas "fechas de registro" diferentes. 

Si desea que se despliegue solamente 1 fecha de registro entonces tenemos que modificar el Document Control para que en lugar de que se puedan registrar varios documentos a la vez, sólamente se pueda registrar 1 documento. Hacerlo de esta forma sin embargo, romperá todo el funcionamiento de las bitácoras registradas anteriormente en el Document Control, porque en la base de datos aún se van a registrar con la fecha de captura, en lugar de la fecha de registro. Ahora, podemos simplemente borrar esos reportes de la base de datos y no tendrán forma de recuperarlos, pero si no desea borrarlos, podemos arreglarlos nosotros mismos moviéndole a la base de datos. 

En pocas palabras, realizar este cambio que está solicitando implica las siguientes tareas:
1. Desacoplar la pantalla de búsqueda de reporte del Document Control de la búsqueda de todas las demás bitácoras para que los cambios realizados aquí no afecten el comportamiento de las otras bitácoras
2. Modificar el comportamiento de la pantalla de captura de Document Control (y de todos los servicios del servidor que atienden el registro de esta bitácora) para que sólamente se pueda capturar 1 documento a la vez, en lugar de poder capturar varios documentos a la vez.
3. Editar en la base de datos los reportes de Document Control capturados anteriormente para que su funcionamiento no se rompa al implementar estos nuevos cambios y para que no haya la necesidad de borrarlos definitivamente

Todo esto implicará varias horas (días) de trabajo, no es un cambio sencillo. Ahora que conoce lo que implica implementar este cambio, ¿desea que trabajemos en ello?

**Comment by delcabo** [comment]
aah entiendo
Sabes, creo que nadie esta capturando mas de 2 reportes en el mismo registro, entonces esta bien si es 1 a la vez...

gracias

**Comment by caom92** [comment]
Bueno, lo implementaré de esa forma entonces, nomás que como le dije, tomará bastante tiempo y recuerde que cobramos en base al tiempo que nos toma hacer el desarrollo. Empezaremos primero implementando los cambios más sencillos y dejaremos éste hasta el último. Le avisaré cuando tengamos novedades con respecto a este issue.

**Comment by delcabo** [comment]
en serio!!! woow
OK dejame ver entonces, tal ve se puede ajustar porque no puedo ahorita..... ahorita justificar el gasto 
por registros que se debe hacer al dia!...

dame unos minutos!

**Comment by delcabo** [comment]
cuanto le estimas $$$$ aprox?

**Comment by caom92** [comment]
Terminé de hacer las modificaciones necesarias en el código del backend, @VMiracle  está trabajando ahora en hacer las modificaciones necesarias en el frontend. [Tiempo total hasta ahora: 2 horas]

**Comment by VMiracle** [comment]
5 horas
