### ISSUE TITLE
Finish Product PDF report

### ISSUE THREAD

**Issue by delcabo** [caom92/Espresso#345]
Buenas tardes

tenemos actulmente el reporte en PDF, pero si requiere una ajustadita para mejor lectura

Tal vez primero si se puede hacer Landscape, un solo encabezado por  pagina y con cuadricula por registro con font pequenos no importa

encabezados abreviados por ejemplo
Washing Water Temperature   =   Wash *F 
Packed Product Temperature = Packed *F

![image](https://user-images.githubusercontent.com/28766240/29893585-6393d918-8d87-11e7-85dc-0eb602890d99.png)

**Comment by VMiracle** [comment]
Hola, para confirmar que entiendo la petición, ¿sería algo así lo que espera como resultado final?

![ejemplo_hecho_en_paint](https://user-images.githubusercontent.com/14243150/29894703-24013ddc-8d8b-11e7-9091-7cce25bd5558.png)

**Comment by VMiracle** [comment]
En Skype se aprobó el formato del ejemplo anterior

**Comment by delcabo** [comment]
perfecto, solo subir el LINK al encabezado, y dejar lo azul como primer linea, y Notes en 2da linea!!
cambiar 1er correct a Weight el 2o Correct a Label

y listo

**Comment by VMiracle** [comment]
Esta sería la versión final, ya generada por el sistema. Estos si serían los labels finales, ¿alguno debería ser cambiado?

![Uploading VersionFinal.png…]()

**Comment by VMiracle** [comment]
![versionfinal](https://user-images.githubusercontent.com/14243150/29896494-0e56f63c-8d92-11e7-80d9-61b00d6c23f3.png)

**Comment by delcabo** [comment]
orales!!! que bien! gracias!

**Comment by VMiracle** [comment]
El reporte ya debe de estar funcionando correctamente en el servidor, cualquier problema no dude en notificarnos

**Comment by caom92** [comment]
[Tiempo total: 2 horas]
