### ISSUE TITLE
Document control

### ISSUE THREAD

**Issue by delcabo** [caom92/Espresso#369]

**Comment by delcabo** [comment]
Hola buenas tardes
cuando quiero correr un reporte en esta opcion, no me da opcion de seleccionar cual reporte en especifico
solo salen TODOS
![image](https://user-images.githubusercontent.com/28766240/30299620-5b0e3e78-9705-11e7-953d-c22edfde37a9.png)

**Comment by VMiracle** [comment]
El problema localizado fue que la lista no se actualiza al cambiar la zona dentro de la página de reportes. Se corregirá a la brevedad

**Comment by caom92** [comment]
Estoy 100% seguro de que éste es duplicado de #346
