### ISSUE TITLE
Ordenar elementos del reporte de Aged Product por fecha

### ISSUE THREAD

**Issue by delcabo** [caom92/Espresso#388]
Como la ven?

![image](https://user-images.githubusercontent.com/28766240/31139882-c224a2e0-a827-11e7-85ae-872514b6d083.png)

**Comment by delcabo** [comment]
Lo amarillo es para que se ajuste en un solo renglon! aunque se corte  no problem

**Comment by delcabo** [comment]
OK la primer peticion fue definitivamente muy ruda!!!  :)
pero se puede hacer esta mientras!! 
reducir "Sale Soon" en 1 renglon y que salga ordenador por DATE....
![image](https://user-images.githubusercontent.com/28766240/31254443-8f852b40-a9dd-11e7-931d-d74821b4c4e6.png)

**Comment by caom92** [comment]
Ya quedo, falta subirlo al servidor de Julio

**Comment by delcabo** [comment]
Equipo el campo BATCH, LOCATION, puede ser opcional o tener 0 por default?
![image](https://user-images.githubusercontent.com/28766240/31288206-cf43d8bc-aa78-11e7-8d4b-6c0571b665ab.png)

**Comment by delcabo** [comment]
un extra! por favor!!
Me pueden cotizar cuanto seria, quitar el campo de Dias de Captura, y que se llene automtico por la fecha actual - DATE y se llene solito el campo y salga en el reporte..
