### ISSUE TITLE
Cambios a LABORATORIOS

### ISSUE THREAD

**Issue by delcabo** [caom92/Espresso#391]
Se puede ajustar el sistema de captura de fechas sin neceisda de darle CERRAR?

**Comment by delcabo** [comment]
Ajuste de pantalla, que no maximize a toda la pantalla, solo un recuadro regualr!!!, ajuste de la seleccion de fecha como esta el Foodsafety manual :)
![image](https://user-images.githubusercontent.com/28766240/31255386-6b309abe-a9e1-11e7-9f4b-28497705e623.png)
![image](https://user-images.githubusercontent.com/28766240/31255407-87698b6e-a9e1-11e7-85fa-4904926ecb69.png)

**Comment by delcabo** [comment]
el boton ENVIAR se pone en gris....   se puede especificar si es PDF solamente en SUBIR DOCUMENTO!
![image](https://user-images.githubusercontent.com/28766240/31255498-03090182-a9e2-11e7-9fef-be7200b185c5.png)

**Comment by delcabo** [comment]
aaah requiere subir primero un estudio!!! oooh!! para que prenda el boton ENVIAR!
pero estudio quedamos que no era necesario! si se puede eliminar OK

**Comment by delcabo** [comment]
me faltaron campos 
ok Fecha (campo de fecha, ingresado por el usuario) _1_
? • Laboratorio (campo abierto de texto)
ok • Zona (campo de tipo lista de selección, tomado de las Zonas guardadas en el sistema)
ok • Productor (campo abierto de texto)_1_
**? • Producto o Área (campo abierto de texto)_1_
? • Notas (campo abierto de texto)
? • Link (campo abierto de texto)**
ok • Fotografía (campo de carga de archivo)2

**Comment by delcabo** [comment]
Busqueda:

No pone por default todos, si solo quiero las fechas el resto de los campos por default "TODOS"
![image](https://user-images.githubusercontent.com/28766240/31255697-04340ac4-a9e3-11e7-9fe3-8b776d6e61dc.png)

**Comment by delcabo** [comment]
Puede poner mas informacion una vez que encuentre registros, tal vez Productor-producto/Area :)
![image](https://user-images.githubusercontent.com/28766240/31255741-3eb55644-a9e3-11e7-90e4-7459fa39b52a.png)

**Comment by delcabo** [comment]
Excelente cuando visualizas el documento!!!!

**Comment by caom92** [comment]
@delcabo  para reportar problemas del proyecto de laboratorios, use [este enlace](https://github.com/caom92/doc-manager/issues) y reporte 1 problema por Issue solamente
