### ISSUE TITLE
Aging Producto (No sale Accion)

### ISSUE THREAD

**Issue by delcabo** [caom92/Espresso#392]
Dia!!  no sale la accion correcttiva en el reporte!

![image](https://user-images.githubusercontent.com/28766240/31399978-e081f2b2-ada2-11e7-8a7a-b8d03d05100f.png)

**Comment by VMiracle** [comment]
El problema se hallaba en autorizaciones, que si se llegaba a editar y guardar una bitácora no se respetaban los valores de la acción correctiva. No se puede recuperar el valor de los reportes capturados previamente, pero los reportes capturados a partir de ahora ya no tendrán este problema.

**Comment by delcabo** [comment]
OK perfecto muchas gracias!!!
