### ISSUE TITLE
Cambios Tijeras y Cuchillos (campos opcionales)

### ISSUE THREAD

**Issue by delcabo** [caom92/Espresso#415]
Quitar candados y dejar campos opcionales (todos)

![image](https://user-images.githubusercontent.com/28766240/36874936-bd517e04-1d62-11e8-9215-13de63f0158a.png)

y de pazo alinear el campo Sanitazied a mismo nivel vertical de Returned!

saludos

**Comment by VMiracle** [comment]
Creo que este es un issue jurásico que no fue cerrado en su momento, si se trata del caso contrario o surge otro problema con esta bitácora, será necesario abrir un issue nuevo
