### ISSUE TITLE
Basculas  (campos encimados)

### ISSUE THREAD

**Issue by delcabo** [caom92/Espresso#420]
En la bitacora de Basculas... salen los campos de captura encimados !

![image](https://user-images.githubusercontent.com/28766240/37364164-fca8481e-26b6-11e8-8bb1-34f99886da91.png)

**Comment by VMiracle** [comment]
Se optó por mover el título de la báscula, de esta manera el campo se quedará como "Lectura" y el nombre quedará arriba.

![image](https://user-images.githubusercontent.com/14243150/37428068-616a0e46-2788-11e8-8e2c-55491fe213f1.png)

Este cambio se verá reflejado en la próxima actualización del día de hoy (14 de marzo)
