### ISSUE TITLE
Aging Report... informacion fuera del cuadro y solo sale 1 registro!

### ISSUE THREAD

**Issue by delcabo** [caom92/Espresso#421]
En el Aging reporte, se sale del margen del cuadro.
y solo sale 1 registro.. 

![image](https://user-images.githubusercontent.com/28766240/37364356-7f6ebeea-26b7-11e8-9619-94d1288cc258.png)

**Comment by VMiracle** [comment]
Este error ya fue corregido y se reflejará en la próxima actualización, que se hará hoy (14 de marzo)
