### ISSUE TITLE
pantalla de Autorizaciones  botones fail!

### ISSUE THREAD

**Issue by delcabo** [caom92/Espresso#422]
en la pantalla de Aproabaciones lo botones no estan funcionando!

 
![image](https://user-images.githubusercontent.com/28766240/37364797-baa625d8-26b8-11e8-8752-eccf54d701fd.png)

**Comment by VMiracle** [comment]
Hola, ¿cuáles son los botones que no funcionan? ¿hacen algo cuando se presiona el botón (mostrar un mensaje o una pantalla de carga) o simplemente no hacen nada?

**Comment by delcabo** [comment]
Se queda cargando solamente en cualquier botton

es decir el KOI se queda girando!

**Comment by delcabo** [comment]
dato curioso!!

a usuario Yaneth le sale pantalla fea y se queda girando en cualquier botton
en usuario tester   t odod bien...

**Comment by delcabo** [comment]
y de hecho se congela la pantalla con usuario Yaneth! :(

**Comment by delcabo** [comment]
probaremos en la misma compu de Yaneth
 con TESTER

**Comment by delcabo** [comment]
orales si funcio TESTER en la compu de Yaneth normal... 
![image](https://user-images.githubusercontent.com/28766240/37428905-f18da062-278a-11e8-8932-3ac2489cb8ed.png)

**Comment by delcabo** [comment]
asi le sale solamente a Veloz, a Wilma, Mariela, Carissa les sale la pagina bien-normalita..

![image](https://user-images.githubusercontent.com/28766240/37429301-1c722ffe-278c-11e8-834d-1c0783e77a64.png)

**Comment by VMiracle** [comment]
El problema de la pantalla extraña ya lo corregimos y se verá reflejada en la actualización que tendrá lugar hoy más tarde (14 de marzo) alrededor de las 4:30

Aunque el de los botones del listado de autorizaciones aún lo estamos viendo
