### ISSUE TITLE
se queda ciclado el proceso cuando se quiere termianar FINISH PRODUCT.

### ISSUE THREAD

**Issue by delcabo** [caom92/Espresso#423]
en la pantalla de Finish product check.

se congela la pantalla al momento de eviar una captura o terminarla...

![image](https://user-images.githubusercontent.com/28766240/37364983-485f35cc-26b9-11e8-9498-3e89da63c9f5.png)

**Comment by VMiracle** [comment]
Hola, ¿se queda así, con la imagen del cargador medio transparente y no hace nada más?
¿la bitácora aparece para el supervisor en la sección de autorizaciones, o todo indica que no fue capturada?

**Comment by delcabo** [comment]
si se quita, pero se regresa a la misma pantalla sin grabar registro

**Comment by delcabo** [comment]
no se registra y el sistema no te avisa que hay bitacora pendiente

**Comment by VMiracle** [comment]
Este problema ya fue arreglado hace tiempo, pero aún tenía pendiente cerrarlo
