### ISSUE TITLE
Scale log... doble click para ESTADO

### ISSUE THREAD

**Issue by delcabo** [caom92/Espresso#424]
en la bitacora de Basculas...

en el campo de ESTADO se requiere darle doble click para que salga el combo

![image](https://user-images.githubusercontent.com/28766240/37365163-eede5d4c-26b9-11e8-8c8e-68e3680e994e.png)

**Comment by delcabo** [comment]
y tambien no deja enviar hasta que llene Accion Correctiva...  (ultimo registro) o campo

![image](https://user-images.githubusercontent.com/28766240/37366411-9ba25d6e-26bd-11e8-960e-ee5bebd90abc.png)

**Comment by VMiracle** [comment]
Los candados de notas y acción correctiva ya fueron retirados y se añadirán a la actualización que haremos hoy (14 de marzo) más tarde
