### ISSUE TITLE
reporte de scissor y knife... sale cuando se quito grupo

### ISSUE THREAD

**Issue by delcabo** [caom92/Espresso#430]
cuando se elimino un grupo, sale en el reporte...

tal vez quitarlo o dejar en blanco..

![image](https://user-images.githubusercontent.com/28766240/37482189-fa7560e6-2840-11e8-8d85-caf8d2d764d7.png)

**Comment by VMiracle** [comment]
Una pregunta, ¿el grupo fue eliminado durante la captura inicial o durante la autorización?

**Comment by delcabo** [comment]
durante la autorizacion

**Comment by VMiracle** [comment]
Acabo de revisar. El checkmark de "Incluir en captura" solo funciona durante la captura inicial, pero en autorizaciones no, dado que la parte de autorizaciones sólo fue hecha con la capacidad de editar el contenido de una bitácora, más no para borrar.

En síntesis, los registros omitidos durante la captura no aparecen en el reporte, pero los que ya llegaron a la autorización solo pueden ser editados y todos aparecerán en el reporte.  Para evitar la confusión de los usuarios, retiraremos ese botón en autorizaciones.

**Comment by delcabo** [comment]
OK  entendido...
pero si desde el inicio se NO " "Incluir en captura""  el registro no aparece verdad?

**Comment by VMiracle** [comment]
Así es, en la captura inicial funciona correctamente

**Comment by delcabo** [comment]
OK Muchas gracias!
este ya quedo!!!
