### ISSUE TITLE
KOI al mero inicio mientras carga la pagina! y otros

### ISSUE THREAD

**Issue by delcabo** [caom92/Espresso#431]
que se ponga el KOI a dar vueltas mientras entra el sistema desde el inicio...
lo de los grados " °F " en la captura de termometros
y que salgan las  imágenes del Doc Control  cuando se imprmen PDF's
 
saludos

**Comment by VMiracle** [comment]
Esto ya se encuentra resuelto, si volviera a surgir un problema relacionado, sírvase abrir un nuevo issue
