### ISSUE TITLE
Cold Room Temperature Control   ajuste de campo!!!

### ISSUE THREAD

**Issue by delcabo** [caom92/Espresso#433]
ajute de campo de registro de Temperatura

Quitar la bandera de " prueba del punto de hielo" 
y ajustar el mismo campo a abierto Alphanumerico.... 

![image](https://user-images.githubusercontent.com/28766240/39143969-3dd43634-46e4-11e8-9f44-79fd859202e6.png)

**Comment by VMiracle** [comment]
Por Skype se acordó añadir un nuevo campo para poder registrar la temperatura relativa. Esto afectó captura, autorizciones, reportes en el sistema/PDF y cambios en la base de datos, así como la comunicación entre el sistema y la base de datos. 

[Tiempo total de desarrollo: 3 horas]
