### ISSUE TITLE
Cool room, que deje captuar fechas anteriores

### ISSUE THREAD

**Issue by delcabo** [caom92/Espresso#434]
Tener la opcion de poder capturar registros con fechas atrazadas, 

![image](https://user-images.githubusercontent.com/28766240/39213626-f24c3282-47c6-11e8-988a-5d470784dd9b.png)

**Comment by VMiracle** [comment]
Finalmente, se agregó esta opción para todas las bitácoras. Se toma como opción por defecto la fecha actual, sin limitar al usuario para cambiar esta. En autorizaciones aún no se permite esta característica, pero si se solicita es posible agregar dicha funcionalidad en un futuro.

![image](https://user-images.githubusercontent.com/14243150/39338089-843ed24e-4975-11e8-8654-caccc7e52e62.png)

[Tiempo total de desarrollo y actualizaciones del servidor: 6 horas]
