### ISSUE TITLE
DAily Scale LOG

### ISSUE THREAD

**Issue by delcabo** [caom92/Espresso#437]
Al momento de aprobar esta bitacora el campo STATUS esta en blanco
![image](https://user-images.githubusercontent.com/28766240/40565664-41a1bdac-6022-11e8-93be-0f5405ee8f09.png)

pero cuando le cambio a ENGLSIH   voaalaaaa
el campo se llena de nueva!!
![image](https://user-images.githubusercontent.com/28766240/40565686-578c9196-6022-11e8-8539-e7e1519c8139.png)

**Comment by VMiracle** [comment]
Este issue ya está corregido y se encuentra en la versión actual, simplemente no se había cerrado
