### ISSUE TITLE
No guarda Acciones correctivas PREOP

### ISSUE THREAD

**Issue by delcabo** [caom92/Espresso#442]
me comento BPM que no guardo las Acciones que se escribieron en el Pre operativo!

![image](https://user-images.githubusercontent.com/28766240/41557254-e348a47c-72f1-11e8-9ee7-d87bc57a4716.png)

**Comment by VMiracle** [comment]
Lo que sucede es que, al marcar un elemento como "aceptable", la opción para marcar una acción correctiva no existe, y por tanto se marca "N/A" como valor por defecto
