### ISSUE TITLE
ajuste de campo a la derecha.. "Calidad"  Finish product check

### ISSUE THREAD

**Issue by delcabo** [caom92/Espresso#445]
Este punto ya se habia pedido hace tiempo!!!

ajuste del campo CALIDAD/QUALITY  que el resultado quepa en 1 sola linea, en este caso que es resultado condicionado.. no es abierto...

![image](https://user-images.githubusercontent.com/28766240/42465168-06d5b8b6-8360-11e8-9dd1-54c18c11769f.png)

**Comment by VMiracle** [comment]
Ya se arregló ese detalle, aumentando el tamaño del campo de Quality y reduciendo el tamaño del campo Origin (considerando que este es un código de 3 letras). Eso se hizo para garantizar que los valores de Quality actuales quepan  en una sola línea, mas esto no influirá en el resto de los campos y su tamaño.

Quedará reflejado en una próxima actualización.
