### ISSUE TITLE
Quitar candados y que borre un registros cuando se presione "-"

### ISSUE THREAD

**Issue by delcabo** [caom92/Espresso#446]
No deja eliminar un registro no deseado!
y quitar al menos los candados de "Washing Water Temp" y CUSTOMERS

![image](https://user-images.githubusercontent.com/28766240/43160786-0330a086-8f3b-11e8-82a1-b5e87a367a83.png)

**Comment by VMiracle** [comment]
El problema de borrar registros no deseados ya fue corregido; en cuanto a la validación (candados), por Skype se retiró esta última petición.

![image](https://user-images.githubusercontent.com/14243150/43345426-57933242-91a2-11e8-98b2-1ea9ac6b8738.png)

Igual dejo constancia de que es posible realizar dicho cambio en un futuro, si se termina considerando necesario
