### ISSUE TITLE
en el modulo de NOUCA anexar Descripcion en busqueda

### ISSUE THREAD

**Issue by delcabo** [caom92/Espresso#452]
poner despues de la fecha lo que quepa por 1 linea del campo de DESCRIPCION en cada registro encontrado segun la busqueda.

![image](https://user-images.githubusercontent.com/28766240/49821740-093c3b80-fd30-11e8-8137-60c387beb149.png)

**Comment by VMiracle** [comment]
Listo, quedará reflejado en la próxima actualización
